apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend-$COLOR_TEST
    environment: $COLOR_TEST
  name: backend-$COLOR_TEST
  namespace: cadrart
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: 'ws'
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    io.kompose.service: backend-$COLOR_TEST
    environment: $COLOR_TEST
status:
  loadBalancer: {}
