apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: cadrart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/cadrart-default: 'true'
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: CADRART_DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_DATABASE
                  name: cadrart-config
            - name: CADRART_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: cadrart-secret
            - name: CADRART_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DATABASE_USER
                  name: cadrart-secret
            - name: CADRART_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_TYPE
                  name: cadrart-config
            - name: CADRART_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: cadrart-config
            - name: CADRART_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PORT
                  name: cadrart-config
            - name: CADRART_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: cadrart-secret
            - name: STATIC_ROOT
              valueFrom:
                configMapKeyRef:
                  key: STATIC_ROOT
                  name: cadrart-config
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: cadrart-config
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: cadrart-config
            - name: CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  key: CORS_ORIGINS
                  name: cadrart-secret
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_DIRECTORY
              value: "/var/log/cadrart"
          image: ghcr.io/manuszep/cadrart2025-backend
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /var/www/static
              name: static-volume
            - mountPath: /var/log/cadrart
              name: logs-volume
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      imagePullSecrets:
        - name: cadrart-registry-key
      restartPolicy: Always
                volumes:
            - name: static-volume
              persistentVolumeClaim:
                claimName: static-volume
            - name: logs-volume
              persistentVolumeClaim:
                claimName: cadrart-logs-pvc
status: {}
