apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
    environment: green
  name: backend
  namespace: cadrart-b
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: 'ws'
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    io.kompose.service: backend
    environment: green
status:
  loadBalancer: {}
